export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_KEYWORD = 'SET_KEYWORD';
export const UPDATE_FOUND_ARTICLES = 'UPDATE_FOUND_ARTICLES';
export const UPDATE_STORE_ARTICLES = 'UPDATE_STORE_ARTICLES';
